baseURL: "https://dp9u0.github.io/algorithmica/"
theme:
- algorithmica
- reveal-hugo
pygmentsUseClasses: true
outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
outputs:
  home:
  - HTML
  - SearchIndex
markup:
  goldmark:
    footnote: false  # katex conflict
    renderer:
      unsafe: true
defaultContentLanguage: zh
sectionPagesMenu: main
languages:
  en:
    title: Algorithmica
    contentDir: content/english
    label: English
    locale: "en-us"
    weight: 1
    params:
      contentDir: content/english
  ru:
    title: Алгоритмика
    contentDir: content/russian
    label: Русский
    locale: "ru-ru"
    weight: 2
    params:
      contentDir: content/russian
  zh:
    title: Algorithmica
    contentDir: content/chinese
    label: 中文
    locale: "zh-cn"
    weight: 3
    params:
      contentDir: content/chinese
params:
  repo: "https://github.com/dp9u0/algorithmica"
  reveal_hugo:
    #theme: white
    slide_number: true
    transition: none
    custom_theme: "slides.sass"
    custom_theme_compile: true
